### ISSUE TITLE
[Feature Request] Alpha support

### ISSUE THREAD

**Issue by fralonra** [seancroach/hex_color#1]
Hi, thanks to the library! It helps get things done easily.

Currently alpha channel is not supported yet, is there any plan to work on it?

**Comment by seancroach** [comment]
Yes! While originally it wasn't in the scope of the project, I see no reason to _not_ support it.

It shouldn't take too long, and a separate type that both supports alpha and can be parsed from 3, 4, 6, and 8-digit hex codes (where 3 and 6 default to an alpha equal to 0) is in the works for version 1.1

**Comment by m-kuzmin** [comment]
How about adding an `a: Option<u8>` instead of a separate type? This shouldn't break any current code and afaik serde has support for not serializing `None`s.

**Comment by seancroach** [comment]
Hello, and sorry for my untimely response to this feature request!

After certain life events that delayed my productivity, and pondering @max-ishere's rewrite, I've opted instead to simply make a breaking change to add RGBA support. Thank you, @fralonra and @m-kuzmin, (and @max-ishere who did the mental groundwork) for helping to improve `hex_color`.

**Comment by m-kuzmin** [comment]
You're welcome. Actually @max-ishere is my personal one that I used by accident so you can just mention @m-kuzmin instead.

Anyway, not sure what you decided with the breaking change. I suppose it's gonna be a revert of a revert of #3?

**Comment by max-ishere** [comment]
> Actually @max-ishere is my personal one that I used by accident so you can just mention @m-kuzmin instead.

Yep.
