### ISSUE TITLE
[Feature Request] Color Inversion

### ISSUE THREAD

**Issue by wildwestrom** [seancroach/hex_color#5]
## Feature Request

- [x] I would like to work on this feature!

Lovely library! I just made a function that naively inverts colors and I'd like to add it as a method to the main struct
```rust
const fn invert_color(color: HexColor) -> HexColor {
    let r = 0xFF - color.r;
    let g = 0xFF - color.g;
    let b = 0xFF - color.b;
    HexColor::new(r, g, b)
}
```
Maybe later I can implement a gamma corrected invert function.

Do you think this is a good idea? If not, I don't mind if you close this.

**Comment by seancroach** [comment]
Hello! Thank you for your interest in improving `hex_color`.

I've adopted your function in version `2.0.0` of `hex_color`. While I am interested in gamma conversions and whatnot, that's a can of worms I'm not rushing to complete myself. If you'd be interested, however, I'd love to hear further feedback and accept any implementations you can provide (with comments, as colors aren't my forté [yet]).

Thanks again!
