### ISSUE TITLE
Printing defaults

### ISSUE THREAD

**Issue by nuzzles** [seancroach/hex_color#8]
Hey! I thought this was abandoned. Thanks for getting around to it all!

Currently `println!("{}", my_color)` will print `#RRGGBB`
Currently `println!("{:?}", my_color)` will print `#RRGGBBAA`

I'm not satisfied with how this works. For one, `{:?}` is supposed to be a debug print. This is standard across Rust. If you rely on the current behavior, it would confuse a code reviewer what's actually going on here.

I was going to suggest next to set the default `Display` to print the full color: `#RRGGBBAA`
And use `#[derive(Debug)]` to handle the debug print, as one would expect.

To maintain functionality, we could add sugary functions for more readability/context:
`color.rgb_str()` and `color.rgba_str()`

**Comment by seancroach** [comment]
As it is right now, it's all working as intended. I'm afraid you're mistaken about how the current formatting is implemented.

To display `#RRGGBBAA` I take advantage of the "alternate" flag for `fmt::Display` as explained [here](https://doc.rust-lang.org/src/alloc/fmt.rs.html#184). By default, this means RGB colors that are displayed or collected as strings via default methods *do* become `#RRGGBB`, and given that this is usually more common than including an alpha channel, it seems like a sane default. However, if people *want* to get `#RRGGBBAA`, they simply have to format via that alternate flag: `format!({my_color:#})` (Note that this is just the alternate flag with the `fmt::Display` selector.

However, `fmt::Debug` is untouched, printing the structure as-is, or using that same alternate flag for pretty printing, which is just a result of me deriving that implementation.

If that doesn't clear things up, or you find that explanation, unsatisfactory, just let me know.

**Comment by seancroach** [comment]
So, can you explain what actually seems wrong? Your primary issue of debug not being predictable is just incorrect. The behavior you've described isn't how the crate actually works.

**Comment by nuzzles** [comment]
Re: debug was incorrect - Thank you for correcting.

Re: alternative print mode being unpredictable is valid.
When you see `format!("{some_struct:#}")` do you know what that alternative print mode will do? There's very little linkage or optics into what it does without looking at the source code. This is tribal knowledge.

I think alternative print modes should always print the same content because of this reason.
e.g. "pretty print json" is OK, because these are equivalent:
```json
{"key":"value"}
```
```json
{
  "key": "value"
}
```

But printing different contents is obscure behavior in my opinion.
So the default should be to print the entire color, in full. Which means alpha included. Remove the alternative print mode since it's not meaningful in this context except to be confusing. Adding similar modes like `color.rgb() -> str` or `color.rgba() -> str` will be more contextual.

**Comment by seancroach** [comment]
Perfectly explained; great point. I'll consider a fix soon, bumping the version to 3.0.0; I'll see what I can do.

**Comment by seancroach** [comment]
@simbleau Let me know if this raises any concerns: https://github.com/seancroach/hex_color/compare/v2.1.0...main

**Comment by nuzzles** [comment]
That looks good to me! Looking forward to the version bump.

**Comment by seancroach** [comment]
Great! Published.
